import {
  BarChart2,
  Bell,
  BookOpen,
  Brain,
  BriefcaseBusiness,
  CheckCircle2,
  FileArchive,
  FileText,
  FolderOpen,
  HeartPulse,
  Landmark,
  Plane,
  Sparkles,
  Target,
  Users,
  Wallet,
  Workflow,
} from 'lucide-react';

export const MODULES = [
  { key: 'tasks', icon: CheckCircle2, bg: 'bg-green-500', label: '/task', sub: 'Open tasks', to: '/tasks' },
  { key: 'reminders', icon: Bell, bg: 'bg-orange-500', label: '/reminder', sub: 'Upcoming reminders', to: '/reminders' },
  { key: 'expenses', icon: Wallet, bg: 'bg-blue-500', label: '/expense', sub: 'Track spending', to: '/expenses' },
  { key: 'notes', icon: FileText, bg: 'bg-purple-500', label: '/note', sub: 'Quick notes', to: '/notes' },
  { key: 'projects', icon: FolderOpen, bg: 'bg-teal-600', label: '/project', sub: 'Project boards', to: '/projects' },
  { key: 'journal', icon: BookOpen, bg: 'bg-pink-500', label: '/journal', sub: 'PIN protected', to: '/journal', locked: true },
  { key: 'analytics', icon: BarChart2, bg: 'bg-indigo-500', label: '/analytics', sub: 'Insights and trends', to: '/analytics' },
  { key: 'chat', icon: Sparkles, bg: 'bg-violet-600', label: '/chat', sub: 'AI assistant', to: '/chat' },
  { key: 'habits', icon: Target, bg: 'bg-emerald-500', label: '/habit', sub: 'Daily streaks', to: '/habits' },
  { key: 'goals', icon: Target, bg: 'bg-lime-600', label: '/goal', sub: 'Milestones and progress', to: '/goals' },
  { key: 'contacts', icon: Users, bg: 'bg-cyan-600', label: '/contact', sub: 'People and follow-ups', to: '/contacts' },
  { key: 'documents', icon: FileArchive, bg: 'bg-red-500', label: '/document', sub: 'Expiring documents', to: '/documents' },
  { key: 'knowledge', icon: Brain, bg: 'bg-fuchsia-600', label: '/knowledge', sub: 'Learning notes', to: '/knowledge' },
  { key: 'health', icon: HeartPulse, bg: 'bg-rose-600', label: '/health', sub: 'Medication and refills', to: '/health' },
  { key: 'travel', icon: Plane, bg: 'bg-sky-600', label: '/travel', sub: 'Trips and checklists', to: '/travel' },
  { key: 'assets', icon: BriefcaseBusiness, bg: 'bg-amber-600', label: '/asset', sub: 'Inventory and warranties', to: '/assets' },
  { key: 'finance-planning', icon: Landmark, bg: 'bg-blue-700', label: '/finance', sub: 'Targets and savings', to: '/finance-planning' },
  { key: 'automation', icon: Workflow, bg: 'bg-slate-500', label: '/automation', sub: 'Rules and routines', to: '/automation' },
];
